
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ClientLenis from "@/templates/ClientLenis"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='antialiased'>
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body className=' antialiased flex w-screen  bg-[#09090C] overflow-x-hidden z-10  '>
        <ClientLenis >

          {children}
        </ClientLenis>
      </body>
    </html>
  )
}
